- app/Http/Controllers/Patient/PatientController.php
- app/Infrastructure/Repositories/Patient/IPatientRepository.php
- app/Infrastructure/Repositories/Patient/PatientRepository.php
- app/Models/Patient.php
- app/Providers/AppServiceProvider.php
- app/UseCase/Patient/PatientService.php
- app/UseCase/Patient/PatientUseCase.php
- routes/api.php
> [feature] get all patients

- app/Http/Controllers/Patient/PatientController.php
- app/Infrastructure/Repositories/Patient/IPatientRepository.php
- app/Infrastructure/Repositories/Patient/PatientRepository.php
- app/UseCase/Patient/PatientService.php
- app/UseCase/Patient/PatientUseCase.php
- routes/api.php
> [feature] get patient detail

- app/Config/Constant.php
- app/Http/Controllers/Patient/Common.php
- app/Http/Controllers/Patient/PatientController.php
- app/Http/Payload/Patient/Payload.php
- app/Infrastructure/Repositories/Patient/IPatientRepository.php
- app/Infrastructure/Repositories/Patient/PatientRepository.php
- app/UseCase/Patient/PatientService.php
- app/UseCase/Patient/PatientUseCase.php
- app/Util/Common.php
- routes/api.php
> [feature] create new patient

- app/Http/Controllers/Patient/PatientController.php
- app/Infrastructure/Repositories/Patient/IPatientRepository.php
- app/Infrastructure/Repositories/Patient/PatientRepository.php
- app/UseCase/Patient/PatientService.php
- app/UseCase/Patient/PatientUseCase.php
- routes/api.php
> [feature] del patient by id

- app/Http/Controllers/AuthController.php
- app/Http/Presenter/Response.php
- package-lock.json
- package.json
- routes/api.php
> fix bug auth

- app/Http/Controllers/Medicine/MedicineController.php
- app/Http/Payload/Medicine/Payload.php
- app/Infrastructure/Migration/medicine.sql
- app/Infrastructure/Repositories/Medicine/IMedicineRepository.php
- app/Infrastructure/Repositories/Medicine/MedicineRepository.php
- app/UseCase/Medicine/MedicineService.php
- app/UseCase/Medicine/MedicineUseCase.php
- routes/api.php
> (feat) updte medicine

- app/Http/Controllers/Category/CategoryController.php
- app/Infrastructure/Define/Category.php
- app/Infrastructure/Migration/medical_registration_form.sql
- app/Infrastructure/Migration/users.sql
- app/Infrastructure/Repositories/Category/CategoryRepository.php
- app/Infrastructure/Repositories/Category/ICategoryRepository.php
- app/Models/Category.php
- app/Models/MedicalRegistrationForm.php
- app/Providers/AppServiceProvider.php
- app/UseCase/Category/CategoryService.php
- app/UseCase/Category/CategoryUseCase.php
- routes/api.php
> (feat) get category by type

- app/Http/Controllers/MedicalRegistrationForm/Common.php
> (feat) get list medical registration form

- app/Http/Controllers/Patient/PatientController.php
- app/Http/Payload/Patient/Payload.php
- app/Infrastructure/Repositories/Patient/IPatientRepository.php
- app/Infrastructure/Repositories/Patient/PatientRepository.php
- app/UseCase/Patient/PatientService.php
- app/UseCase/Patient/PatientUseCase.php
- routes/api.php
> (feat) update patient

- app/Exceptions/CustomExceptionHandler.php
- app/Http/Kernel.php
- app/Http/Middleware/PermissionAllowMiddleware.php
- app/Http/Middleware/VerifyMiddleware.php
- app/Infrastructure/Define/Status.php
- app/Models/Status.php
- routes/api.php
> (feat) add permission and verify middleware

- app/Http/Controllers/MedicalRegistrationForm/MedicalRegistrationFormController.php
- app/Http/Kernel.php
- app/Http/Payload/MedicalRegistrationForm/Payload.php
- app/Infrastructure/Define/Status.php
- app/Infrastructure/Migration/medical_registration_form.sql
- app/Infrastructure/Repositories/MedicalRegistrationForm/IMedicalRegistrationFormRepository.php
- app/Infrastructure/Repositories/MedicalRegistrationForm/MedicalRegistrationFormRepository.php
- app/UseCase/MedicalRegistrationForm/MedicalRegistrationFormService.php
- app/UseCase/MedicalRegistrationForm/MedicalRegistrationFormUseCase.php
- routes/api.php
> (feat) update status medical form

- app/Http/Controllers/MedicalRegistrationForm/Common.php
- app/Infrastructure/Repositories/MedicalRegistrationForm/MedicalRegistrationFormRepository.php
- app/Models/MedicalRegistrationForm.php
> (feat) add status for medical form

- app/Http/Controllers/MedicalRegistrationForm/Common.php
- app/Http/Controllers/MedicalRegistrationForm/MedicalRegistrationFormController.php
- app/Http/Kernel.php
- app/Infrastructure/Repositories/MedicalRegistrationForm/IMedicalRegistrationFormRepository.php
- app/Infrastructure/Repositories/MedicalRegistrationForm/MedicalRegistrationFormRepository.php
- app/UseCase/MedicalRegistrationForm/MedicalRegistrationFormService.php
- app/UseCase/MedicalRegistrationForm/MedicalRegistrationFormUseCase.php
- routes/api.php
> (feat) get list medical form of doctor and modify verify middleware

- app/Http/Controllers/MedicalRegistrationForm/Common.php
- app/Http/Controllers/MedicalRegistrationForm/MedicalRegistrationFormController.php
- app/Infrastructure/Repositories/MedicalRegistrationForm/IMedicalRegistrationFormRepository.php
- app/Infrastructure/Repositories/MedicalRegistrationForm/MedicalRegistrationFormRepository.php
- app/UseCase/MedicalRegistrationForm/MedicalRegistrationFormService.php
- app/UseCase/MedicalRegistrationForm/MedicalRegistrationFormUseCase.php
- routes/api.php
> (feat) get list medical form complete of patient

- app/Http/Controllers/TestResult/Common.php
- app/Http/Controllers/TestResult/TestResultController.php
- app/Http/Payload/TestResult/Payload.php
- app/Infrastructure/Define/Status.php
- app/Infrastructure/Migration/fee.sql
- app/Infrastructure/Repositories/Fee/FeeRepository.php
- app/Infrastructure/Repositories/Fee/IFeeRepository.php
- app/Infrastructure/Repositories/Prescription/IPrescriptionRepository.php
- app/Infrastructure/Repositories/Prescription/PrescriptionRepository.php
- app/Infrastructure/Repositories/TestResult/ITestResultRepository.php
- app/Infrastructure/Repositories/TestResult/TestResultRepository.php
- app/Models/Fee.php
- app/Models/Prescription.php
- app/Models/PrescriptionMedicine.php
- app/Models/TestResult.php
- app/Providers/AppServiceProvider.php
- app/UseCase/TestResult/TestResultService.php
- app/UseCase/TestResult/TestResultUseCase.php
- routes/api.php
> (feat) create test result fee

- app/Http/Controllers/MedicalRegistrationForm/Common.php
- app/Infrastructure/Migration/category.sql
> (feat) add cost for category service

- app/Infrastructure/Define/Category.php
- app/UseCase/TestResult/TestResultService.php
> (fix) add type for fees

- app/UseCase/MedicalRegistrationForm/MedicalRegistrationFormService.php
> (feat) create fee when create medical form

- app/Http/Controllers/MedicalRegistrationForm/Common.php
- app/Infrastructure/Repositories/MedicalRegistrationForm/MedicalRegistrationFormRepository.php
- app/Models/Fee.php
- app/Models/MedicalRegistrationForm.php
- app/Models/Status.php
- app/Providers/AppServiceProvider.php
> (feat) add status medical registration form

- app/Http/Controllers/TestResult/TestResultController.php
- app/Http/Payload/TestResult/Payload.php
- app/Infrastructure/Repositories/Fee/FeeRepository.php
- app/Infrastructure/Repositories/Fee/IFeeRepository.php
- app/UseCase/TestResult/TestResultService.php
- routes/api.php
> (feat) update status payment test result to paid

- app/Infrastructure/Migration/fee.sql
- app/Infrastructure/Repositories/MedicalRegistrationForm/IMedicalRegistrationFormRepository.php
- app/Infrastructure/Repositories/MedicalRegistrationForm/MedicalRegistrationFormRepository.php
- app/Infrastructure/Repositories/Patient/IPatientRepository.php
- app/Infrastructure/Repositories/Patient/PatientRepository.php
- app/UseCase/Patient/PatientService.php
> (fix) fix delete patient cascade medical form and fee
